INSERT INTO `country` (`country`) VALUES
('Argentina'),
('Austria'),
('Bangladesh'),
('Belarus'),
('Brazil'),
('China'),
('Czech Republic'),
('France'),
('Germany'),
('India'),
('Indonesia'),
('Italy'),
('Japan'),
('Malaysia'),
('Mexico'),
('Pakistan'),
('Portugal'),
('Russia'),
('South Korea'),
('Spain'),
('Taiwan'),
('Thailand'),
('Turkey'),
('United Kingdom'),
('United States');

-- --------------------------------------------------------

INSERT INTO `manufacturer` (`name`, `country`, `rating`) VALUES
('AJP', 'Portugal', '3'),
('Aliança', 'Portugal', '5'),
('Alligator', 'United States', '4'),
('APP', 'Indonesia', '5'),
('Aprilia', 'Italy', '10'),
('Ariel', 'United Kingdom', '8'),
('Arlen Ness', 'United States', '4'),
('Atlas PTY', 'Bangladesh', '4'),
('Avinton', 'France', '7'),
('Bajaj Auto', 'India', '4'),
('Benelli', 'Italy', '8'),
('Beta Motor', 'Italy', '8'),
('Bigbull Motor', 'Thailand', '7'),
('Bimota', 'Italy', '7'),
('Black Jack Chopper', 'United States', '6'),
('Blata', 'Czech Republic', '7'),
('BMW', 'Germany', '10'),
('Borile', 'Italy', '7'),
('Boss Hoss', 'United States', '5'),
('Brammo', 'United States', '6'),
('Bultaco', 'Spain', '9'),
('Casal', 'Portugal', '6'),
('CCM', 'United Kingdom', '7'),
('CFMoto', 'China', '6'),
('Cleveland CycleWer', 'United States', '7'),
('Confederate MC', 'United States', '6'),
('Conquistador', 'Portugal', '6'),
('Daelim', 'South Korea', '8'),
('Dafra Motos', 'Brazil', '7'),
('Dayun', 'China', '6'),
('Derbi', 'Spain', '8'),
('Ducati', 'Italy', '10'),
('Dural', 'Portugal', '5'),
('Eagle Ind', 'Pakistan', '3'),
('Erik Buell Racing', 'United States', '6'),
('Fantic Motor', 'Italy', '7'),
('Gas Gas', 'Spain', '8'),
('Genata', 'China', '8'),
('Ghezzi & Brian', 'Italy', '6'),
('Gilera', 'Italy', '5'),
('Golden Bee', 'Taiwan', '7'),
('Hamza', 'Pakistan', '3'),
('Hanway', 'China', '4'),
('Haojue', 'China', '5'),
('Harley-Davidson', 'United States', '9'),
('Hartford', 'Taiwan', '7'),
('Hero MotoCorp', 'India', '4'),
('Hesketh', 'United Kingdom', '7'),
('Honda', 'Japan', '10'),
('Horex', 'Germany', '9'),
('Huansong', 'China', '6'),
('Husqvarna', 'Austria', '8'),
('Hyosung', 'South Korea', '8'),
('IMZ-Ural', 'Russia', '5'),
('Indian', 'United States', '9'),
('Itaika', 'Mexico', '5'),
('Janus MC', 'United States', '7'),
('Jawa', 'Czech Republic', '8'),
('Jialing', 'China', '7'),
('Jianshe', 'China', '7'),
('Kanuni', 'Turkey', '5'),
('Kasinski Motos', 'Brazil', '7'),
('Kawasaki', 'Japan', '9'),
('KTM', 'Austria', '7'),
('Kymco', 'Taiwan', '7'),
('Laverda', 'Italy', '7'),
('Lingben', 'China', '6'),
('LML', 'India', '6'),
('Loncin', 'China', '3'),
('Mahindra', 'India', '5'),
('Maico', 'Germany', '9'),
('Matchless', 'United Kingdom', '6'),
('Megelli Motorcycle', 'United Kingdom', '8'),
('Métisse', 'United Kingdom', '6'),
('Mican motors', 'China', '3'),
('Minarelli', 'Italy', '6'),
('Minerva', 'Indonesia', '2'),
('Minsk', 'Belarus', '6'),
('Modenas', 'Malaysia', '6'),
('Montesa', 'Spain', '8'),
('Monto Motors', 'India', '4'),
('Moto Guzzi', 'Italy', '10'),
('MotoCzysz', 'United States', '6'),
('Motus', 'United States', '7'),
('Mustang MC', 'United States', '8'),
('MZ', 'Germany', '9'),
('Norton', 'United Kingdom', '9'),
('Nozomi', 'Indonesia', '4'),
('Ossa', 'Spain', '7'),
('Outbreak Customz', 'United States', '7'),
('Peugeot', 'France', '7'),
('Piaggio', 'Italy', '9'),
('Platinum Motor', 'Thailand', '6'),
('Qianjiang', 'China', '6'),
('Qingqi', 'China', '4'),
('Rieju', 'Spain', '7'),
('Road Prince', 'Pakistan', '3'),
('Rokon', 'United States', '8'),
('Sachs', 'Germany', '9'),
('Sanglas', 'Spain', '6'),
('Scomadi', 'United Kingdom', '9'),
('Scorpa', 'France', '6'),
('Sherco', 'France', '6'),
('Siambretta', 'Argentina', '6'),
('Singer PTY', 'Bangladesh', '3'),
('Solex', 'France', '5'),
('Stallions', 'Thailand', '7'),
('Suzuki', 'Japan', '9'),
('Thumpstar', 'China', '2'),
('Tiger', 'Thailand', '7'),
('Trent MC', 'Pakistan', '3'),
('Triumph', 'United Kingdom', '9'),
('TVS Motor', 'India', '6'),
('Vertemati', 'Italy', '5'),
('Viar', 'Indonesia', '3'),
('Victory', 'United States', '7'),
('Voskhod', 'Russia', '4'),
('Vyrus', 'Italy', '5'),
('Walton Hi-Tech', 'Bangladesh', '4'),
('Yamaha', 'Japan', '9'),
('Yo Bykes', 'India', '4'),
('Zanella', 'Argentina', '5');